const ADULT_KEYWORDS = [
  // ──────────────────────────────────────────────
  // Sex toys — core terms + plurals
  // ──────────────────────────────────────────────
  'dildo', 'dildos',
  'vibrator', 'vibrators', 'vibrating',
  'sex toy', 'sex toys', 'sextoy', 'sextoys',
  'adult toy', 'adult toys',
  'pleasure toy', 'pleasure toys',
  'intimate toy', 'intimate toys',
  'erotic toy', 'erotic toys',

  // Vibrator types
  'bullet vibrator', 'bullet vibe',
  'rabbit vibrator', 'rabbit vibe',
  'wand vibrator', 'wand massager', 'wand vibe',
  'magic wand vibrator',
  'g-spot vibrator', 'g spot vibrator',
  'clitoral vibrator', 'clit vibrator', 'clit vibe',
  'finger vibrator', 'finger vibe',
  'egg vibrator', 'vibrating egg',
  'remote vibrator', 'remote vibe',
  'panty vibrator', 'panty vibe',
  'couple vibrator', 'couples vibrator',
  'thrusting vibrator', 'pulsating vibrator',
  'mini vibrator', 'mini vibe',
  'discreet vibrator',
  'waterproof vibrator',
  'rechargeable vibrator',
  'app controlled vibrator',
  'vibrating panties',
  'vibrating underwear',

  // Dildo types
  'realistic dildo', 'realistic dildos',
  'silicone dildo', 'glass dildo', 'metal dildo',
  'suction cup dildo', 'suction dildo',
  'double ended dildo', 'double dildo',
  'thrusting dildo',
  'squirting dildo',
  'inflatable dildo',
  'huge dildo', 'large dildo', 'big dildo', 'monster dildo',
  'fantasy dildo',
  'tentacle dildo',
  'animal dildo',

  // Butt plugs & anal toys
  'butt plug', 'butt plugs', 'buttplug', 'buttplugs',
  'anal plug', 'anal plugs',
  'anal beads', 'anal bead',
  'anal toy', 'anal toys',
  'anal vibrator',
  'anal dildo',
  'prostate massager', 'prostate massagers',
  'prostate stimulator',
  'prostate vibrator',
  'prostate toy',
  'anal trainer', 'anal training',
  'anal hook',
  'butt stuff',
  'jewel plug', 'jeweled plug',
  'tail plug', 'fox tail plug', 'bunny tail plug',
  'inflatable plug',

  // Cock rings & penis toys
  'cock ring', 'cock rings', 'cockring', 'cockrings',
  'penis ring', 'penis rings',
  'vibrating ring', 'vibrating cock ring',
  'erection ring',
  'penis pump', 'penis pumps',
  'penis sleeve', 'penis sleeves',
  'penis extender', 'penis extenders',
  'penis enlarger',
  'cock cage', 'cock cages',
  'cock sleeve',
  'dick ring',
  'ball stretcher', 'ball stretchers',
  'ball ring',
  'glans ring',
  'penis vibrator',

  // Male masturbators
  'fleshlight', 'fleshlights',
  'masturbator', 'masturbators',
  'male masturbator', 'male masturbators',
  'masturbation sleeve', 'masturbation cup',
  'pocket pussy', 'pocket pussies',
  'stroker', 'strokers',
  'onahole',
  'tenga', 'tenga egg',
  'blowjob toy', 'blowjob machine',
  'automatic masturbator',
  'vibrating stroker',
  'male sex toy', 'male sex toys',

  // Strap-ons & harnesses
  'strap-on', 'strap on', 'strapon',
  'strap-ons', 'strap ons', 'strapons',
  'strapless strap',
  'harness dildo',
  'strap on harness', 'strap-on harness',
  'strap on dildo', 'strap-on dildo',
  'pegging', 'pegging kit', 'pegging toy',
  'hollow strap',
  'double strap on',

  // Kegel & love eggs
  'kegel balls', 'kegel ball',
  'kegel exerciser',
  'ben wa balls', 'ben wa',
  'love egg', 'love eggs',
  'yoni egg', 'yoni eggs',
  'pelvic floor trainer',
  'vibrating egg',

  // Sex dolls & machines
  'sex doll', 'sex dolls',
  'love doll', 'love dolls',
  'blow up doll',
  'inflatable doll',
  'sex machine', 'sex machines',
  'fucking machine',
  'sex robot',
  'torso toy',

  // Sex furniture & accessories
  'sex swing', 'sex swings',
  'sex pillow', 'sex pillows',
  'sex furniture',
  'sex blanket',
  'sex wedge', 'sex ramp',
  'liberator',
  'sex sling',
  'sex position cushion',
  'door swing',

  // Nipple toys
  'nipple clamp', 'nipple clamps',
  'nipple sucker', 'nipple suckers',
  'nipple toy', 'nipple toys',
  'nipple vibrator',
  'nipple pump',
  'nipple ring',
  'nipple chain',
  'nipple stimulator',
  'breast pump toy',
  'nipple cover',

  // ──────────────────────────────────────────────
  // BDSM, bondage & fetish
  // ──────────────────────────────────────────────
  'bdsm',
  'bondage', 'bondage kit', 'bondage set', 'bondage gear',
  'handcuffs', 'handcuff',
  'wrist cuffs', 'ankle cuffs',
  'ball gag', 'ball gags',
  'mouth gag', 'bit gag', 'ring gag', 'spider gag',
  'blindfold', 'blindfolds',
  'dominatrix', 'domination', 'domme',
  'submissive', 'submission', 'sub training',
  'slave collar', 'slave collars',
  'collar and leash', 'collar leash',
  'choker collar',
  'fetish', 'fetish wear', 'fetish gear', 'fetish clothing',
  'whip', 'whips',
  'flogger', 'floggers',
  'paddle', 'paddles', 'spanking paddle',
  'spanking', 'spank',
  'riding crop', 'riding crops',
  'cane', 'discipline cane',
  'restraint', 'restraints', 'restraint kit',
  'rope bondage', 'bondage rope',
  'shibari', 'shibari rope',
  'hogtie', 'hog tie',
  'spreader bar', 'spreader bars',
  'chastity', 'chastity cage', 'chastity belt', 'chastity device',
  'cage device',
  'electrostim', 'electrostimulation',
  'electro sex', 'e-stim',
  'wartenberg', 'wartenberg wheel',
  'candle wax play', 'wax play',
  'sensation play',
  'impact play',
  'breath play',
  'edge play',
  'bondage tape',
  'body restraint',
  'under bed restraint',
  'door restraint',
  'sex dungeon',
  'dungeon furniture',
  'st andrews cross',
  'sex bench',
  'spanking bench',
  'sex cage',
  'bondage bed',
  'gimp mask', 'gimp suit',
  'latex mask', 'leather mask',
  'hood mask',
  'posture collar',
  'armbinder',
  'body bag bondage',
  'muzzle gag',
  'humbler',
  'cock and ball torture', 'cbt toy',

  // ──────────────────────────────────────────────
  // Lingerie & adult clothing
  // ──────────────────────────────────────────────
  'lingerie set', 'lingerie sets',
  'sexy lingerie', 'erotic lingerie',
  'see through lingerie', 'sheer lingerie',
  'crotchless', 'crotchless panties', 'crotchless thong',
  'crotchless bodysuit', 'crotchless lingerie',
  'open crotch',
  'edible underwear', 'edible panties',
  'cupless', 'cupless bra', 'cupless lingerie',
  'open cup bra', 'shelf bra',
  'assless', 'assless chaps',
  'thong bodysuit',
  'body stocking', 'body stockings', 'bodystocking',
  'fishnet bodysuit', 'fishnet body',
  'sexy costume', 'sexy costumes',
  'sexy outfit', 'sexy outfits',
  'sexy nurse', 'sexy maid', 'sexy schoolgirl',
  'sexy cop', 'sexy devil', 'sexy angel',
  'sexy halloween', 'adult costume', 'adult costumes',
  'stripper', 'stripper pole', 'stripper outfit',
  'pole dancing kit',
  'peek-a-boo', 'peekaboo bra',
  'latex suit', 'latex outfit', 'latex dress', 'latex catsuit',
  'pvc outfit', 'pvc dress', 'pvc catsuit',
  'leather harness', 'body harness', 'chest harness',
  'garter belt', 'garter set',
  'babydoll lingerie', 'babydoll nightie',
  'corset lingerie',
  'teddy lingerie',
  'chemise lingerie',
  'pasties', 'nipple pasties',
  'g-string', 'g string', 'micro thong',
  'micro bikini',

  // ──────────────────────────────────────────────
  // Lubricants, creams & enhancement
  // ──────────────────────────────────────────────
  'lubricant', 'lubricants',
  'lube', 'lubes',
  'personal lubricant',
  'warming lube', 'cooling lube',
  'flavored lube', 'flavoured lube',
  'anal lube', 'anal lubricant',
  'silicone lube', 'water based lube',
  'massage oil', 'massage oils',
  'edible massage',
  'sensual massage oil',
  'arousal gel', 'arousal cream', 'arousal oil',
  'stimulating gel', 'stimulating cream',
  'delay spray', 'delay cream',
  'numbing cream', 'numbing spray',
  'desensitizing',
  'enlargement', 'enlargement pill', 'enlargement cream',
  'enhancement pill', 'male enhancement',
  'libido', 'libido booster',
  'aphrodisiac', 'aphrodisiacs',
  'sex oil', 'sex cream',
  'erection cream', 'erection pill',
  'viagra', 'cialis',
  'sexual wellness',
  'intimate wash',
  'feminine wash',
  'toy cleaner',

  // ──────────────────────────────────────────────
  // Explicit body part terms
  // ──────────────────────────────────────────────
  'penis', 'penises',
  'vagina', 'vaginas', 'vaginal',
  'clitoris', 'clitoral', 'clit',
  'vulva',
  'labia',
  'testicle', 'testicles', 'testes',
  'scrotum',
  'phallus', 'phallic',
  'orgasm', 'orgasms', 'orgasmic',
  'erection', 'erections',
  'ejaculation', 'ejaculate',
  'erectile',
  'foreskin',
  'glans',
  'g-spot', 'g spot',
  'a-spot',
  'p-spot',

  // ──────────────────────────────────────────────
  // Explicit content, media & industry
  // ──────────────────────────────────────────────
  'erotic', 'erotica',
  'pornography', 'porn', 'porno',
  'xxx',
  'nsfw',
  'nude', 'nudes',
  'nudity', 'nudist',
  'naked',
  'hentai', 'doujin', 'doujinshi',
  'yaoi', 'yuri', 'ecchi', 'futanari',
  'rule 34',
  'ahegao',
  'adult dvd', 'adult film', 'adult video',
  'adult content', 'adult magazine',
  'adult comic', 'adult manga', 'adult anime',
  'playboy', 'playgirl', 'penthouse',
  'hustler',
  'kama sutra', 'kamasutra',
  'sex guide', 'sex handbook',
  'sex position', 'sex positions',
  'sex game', 'sex games',
  'sex card', 'sex cards',
  'sex dice',
  'sex coupon', 'sex coupons',
  'strip poker',
  'sexy board game',
  'truth or dare adult',

  // ──────────────────────────────────────────────
  // Condoms & protection
  // ──────────────────────────────────────────────
  'condom', 'condoms',
  'dental dam', 'dental dams',
  'female condom',
  'flavored condom', 'flavoured condom',
  'ribbed condom', 'textured condom',
  'ultra thin condom',
  'magnum condom',
  'lambskin condom',
  'internal condom',

  // ──────────────────────────────────────────────
  // Slang, vulgar & common search terms
  // ──────────────────────────────────────────────
  'cock', 'cocks',
  'dick', 'dicks',
  'pussy', 'pussies',
  'ass plug',
  'ass toy',
  'booty plug',
  'jerk off', 'jerkoff',
  'wank', 'wanking',
  'cum', 'cumshot',
  'creampie',
  'deepthroat', 'deep throat',
  'blowjob', 'blow job',
  'handjob', 'hand job',
  'rimjob', 'rim job',
  'titjob', 'tit job',
  'footjob', 'foot job',
  'facial cumshot',
  'anal sex',
  'oral sex',
  'butt sex',
  'scissoring',
  'queef',
  'squirt', 'squirting',
  'fisting',
  'fingering',
  'double penetration',
  'triple penetration',
  'thrusting',

  // ──────────────────────────────────────────────
  // Adult lifestyle & services
  // ──────────────────────────────────────────────
  'glory hole',
  'swinger', 'swingers',
  'orgy',
  'threesome', 'foursome',
  'gangbang', 'gang bang',
  'milf',
  'dilf',
  'cougar',
  'sugar daddy', 'sugar baby', 'sugar mama',
  'escort', 'escorts',
  'cam girl', 'cam boy', 'cam model',
  'camgirl', 'camboy',
  'onlyfans', 'only fans',
  'fansly', 'manyvids',
  'chaturbate',
  'sex work', 'sex worker',
  'sensual massage',
  'happy ending',
  'tantric', 'tantric massage',
  'nuru massage',
  'body to body massage',
  'erotic massage',
  'lap dance', 'lapdance',
  'strip club', 'stripclub',
  'gentlemens club',
  'brothel',
  'red light district',
  'call girl',
  'dominatrix for hire',
  'phone sex',
  'sexting',

  // ──────────────────────────────────────────────
  // Brand names commonly associated with adult products
  // ──────────────────────────────────────────────
  'lovense',
  'lelo',
  'we-vibe', 'we vibe', 'wevibe',
  'satisfyer',
  'hitachi magic wand',
  'bad dragon',
  'doc johnson',
  'adam and eve', 'adam & eve',
  'fleshlight',
  'tenga',
  'fun factory',
  'dame products',
  'njoy', 'njoy pure wand',
  'aneros',
  'tantus',
  'je joue',
  'womanizer',
  'zalo',
  'svakom',

  // ──────────────────────────────────────────────
  // Miscellaneous & edge cases
  // ──────────────────────────────────────────────
  'masturbation',
  'foreplay',
  'afterglow',
  'sexual stimulation',
  'sexual pleasure',
  'intimate massager',
  'intimate vibrator',
  'personal massager',
  'back massager adult',
  'clitoral suction',
  'suction toy',
  'tongue vibrator',
  'rose vibrator', 'rose toy', 'rose vibe',
  'pussy pump',
  'clit sucker', 'clit sucking',
  'pleasure wand',
  'adult novelty', 'adult novelties',
  'adult store', 'adult shop',
  'sex shop',
  'sexy gift', 'sexy gifts',
  'bachelorette party adult',
  'penis candle', 'penis candy', 'penis cake',
  'boob candle', 'boob mug',
  'body chocolate', 'body paint adult',
  'edible body',
  'warming massage',
  'couples kit', 'couples toy', 'couples set',
  'fetish mask',
  'leather whip',
  'leather paddle',
  'leather collar',
  'choking',
  'gagging',
]

const keywordPatterns = ADULT_KEYWORDS.map(
  (kw) => new RegExp(`\\b${kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i')
)

export function isAdultContent(title: string | null | undefined): boolean {
  if (!title) return false
  return keywordPatterns.some((pattern) => pattern.test(title))
}
