const ADULT_KEYWORDS = [
  // Sex toys & devices
  'dildo',
  'vibrator',
  'sex toy',
  'sex toys',
  'butt plug',
  'buttplug',
  'anal plug',
  'anal beads',
  'anal toy',
  'cock ring',
  'cockring',
  'fleshlight',
  'penis pump',
  'penis ring',
  'penis sleeve',
  'penis extender',
  'prostate massager',
  'prostate stimulator',
  'g-spot',
  'g spot',
  'clitoral',
  'clit stimulator',
  'clit vibrator',
  'clit sucker',
  'masturbator',
  'masturbation',
  'male masturbator',
  'pocket pussy',
  'love egg',
  'love doll',
  'sex doll',
  'sex machine',
  'sex swing',
  'sex pillow',
  'sex furniture',
  'sex position',
  'pleasure toy',
  'pleasure wand',
  'adult toy',
  'adult novelty',
  'adult store',
  'wand massager',
  'magic wand vibrator',
  'rabbit vibrator',
  'bullet vibrator',
  'thrusting',
  'suction cup dildo',
  'realistic dildo',
  'double ended',
  'double penetration',
  'kegel balls',
  'ben wa balls',

  // Strap-ons (all variations)
  'strap-on',
  'strapon',
  'strap on',
  'strapless strap',
  'pegging',
  'harness dildo',
  'strap on harness',
  'strap on dildo',
  'strap-on harness',
  'strap-on dildo',

  // BDSM & fetish
  'bondage',
  'handcuffs',
  'ball gag',
  'nipple clamp',
  'nipple clamps',
  'nipple sucker',
  'nipple toy',
  'bdsm',
  'dominatrix',
  'domination',
  'submissive',
  'submission',
  'fetish',
  'fetish wear',
  'whip',
  'flogger',
  'paddle',
  'spanking',
  'riding crop',
  'collar and leash',
  'slave collar',
  'choker collar',
  'restraint',
  'restraints',
  'rope bondage',
  'shibari',
  'blindfold',
  'hogtie',
  'spreader bar',
  'chastity',
  'chastity cage',
  'chastity belt',
  'cage device',
  'electrostim',
  'electro sex',
  'wartenberg',
  'candle wax play',

  // Lingerie & adult clothing
  'lingerie set',
  'crotchless',
  'crotchless panties',
  'edible underwear',
  'sexy costume',
  'sexy outfit',
  'sexy lingerie',
  'erotic lingerie',
  'stripper',
  'stripper pole',
  'stripper outfit',
  'pole dancing kit',
  'body stocking',
  'fishnet bodysuit',
  'see through lingerie',
  'peek-a-boo',
  'open cup bra',
  'cupless',
  'assless',
  'thong bodysuit',
  'latex suit',
  'latex outfit',
  'pvc outfit',
  'leather harness',
  'body harness',
  'sexy nurse',
  'sexy maid',
  'sexy schoolgirl',

  // Lubricants & enhancement
  'lubricant',
  'lube',
  'personal lubricant',
  'warming lube',
  'flavored lube',
  'anal lube',
  'silicone lube',
  'massage oil',
  'edible massage',
  'arousal gel',
  'arousal cream',
  'delay spray',
  'numbing cream',
  'enlargement',
  'enhancement pill',
  'libido',
  'aphrodisiac',

  // Explicit body part terms
  'penis',
  'vagina',
  'clitoris',
  'orgasm',
  'erection',
  'ejaculation',
  'erectile',
  'vulva',
  'labia',
  'testicle',
  'scrotum',
  'phallus',
  'phallic',

  // Explicit content / media
  'erotic',
  'erotica',
  'pornography',
  'porn',
  'xxx',
  'nsfw',
  'nude',
  'nudity',
  'naked',
  'hentai',
  'adult dvd',
  'adult film',
  'adult video',
  'adult content',
  'adult magazine',
  'playboy',
  'playgirl',
  'kama sutra',
  'kamasutra',
  'sex guide',
  'sex position',
  'sex game',
  'sex card',
  'sex dice',
  'strip poker',
  'sexy board game',

  // Condoms & protection
  'condom',
  'condoms',
  'dental dam',
  'female condom',
  'flavored condom',
  'ribbed condom',
  'ultra thin condom',

  // Miscellaneous adult
  'glory hole',
  'sex dungeon',
  'swinger',
  'orgy',
  'threesome',
  'gangbang',
  'milf',
  'cougar',
  'sugar daddy',
  'escort',
  'cam girl',
  'cam boy',
  'onlyfans',
  'only fans',
  'sex work',
  'sex worker',
  'sensual massage',
  'happy ending',
  'tantric',
  'tantric massage',
]

const keywordPatterns = ADULT_KEYWORDS.map(
  (kw) => new RegExp(`\\b${kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i')
)

export function isAdultContent(title: string | null | undefined): boolean {
  if (!title) return false
  return keywordPatterns.some((pattern) => pattern.test(title))
}
